version: "3"
services:
  application: 
    build: .
    image: ${IMAGE_NAME}
    container_name: regression
    ports:
      - "8080:8080"
    volumes:
      - ./artifacts:/app/artifacts
      - ./logs:/app/logs
      - ./mlruns:/app/mlruns
